/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JTable;
import modelo.Conexion;
import modelo.Permisos;
import modelo.Producto;
import modelo.Traspaso;

/**
 *
 * @author ainiguez
 */
public class ifrmConsultaTraspaso extends javax.swing.JInternalFrame {
    Main mp;
    JDesktopPane Escritorio;
    Permisos permiso;
    Producto p;
    Traspaso tra;
    Conexion con;
    
    //(this,Escritorio,permiso,producto)
    public ifrmConsultaTraspaso(Main mp,JDesktopPane desk,Permisos per,Producto prod) {
        initComponents();
        this.mp = mp;
        this.Escritorio = desk;
        this.permiso = per;
        this.p = prod;
        
        con = new Conexion();
        tra = new Traspaso(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panHerramientas = new javax.swing.JPanel();
        comboTipo = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTraspaso = new javax.swing.JTable();
        panBotones = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setResizable(true);
        setTitle("Consuklta de traspasos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panHerramientas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "ID Traspaso", "Origen", "Destino" }));
        comboTipo.setSelectedIndex(-1);
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel1.setText("Mostrar");

        javax.swing.GroupLayout panHerramientasLayout = new javax.swing.GroupLayout(panHerramientas);
        panHerramientas.setLayout(panHerramientasLayout);
        panHerramientasLayout.setHorizontalGroup(
            panHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHerramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHerramientasLayout.setVerticalGroup(
            panHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHerramientasLayout.createSequentialGroup()
                .addGroup(panHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        panHerramientasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboTipo, jLabel1, txtBusqueda});

        tablaTraspaso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaTraspaso);

        panBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesLayout = new javax.swing.GroupLayout(panBotones);
        panBotones.setLayout(panBotonesLayout);
        panBotonesLayout.setHorizontalGroup(
            panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panBotonesLayout.setVerticalGroup(
            panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                    .addComponent(panHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        mp.ventConsultaTras = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        comboTipo.setSelectedIndex(0);
        crearTabla(0);
    }//GEN-LAST:event_formInternalFrameOpened

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        crearTabla(comboTipo.getSelectedIndex());
    }//GEN-LAST:event_comboTipoActionPerformed

    public void crearTabla(int tipo){
        
        switch(tipo){
            case 0:
                tablaTraspaso.setModel(tra.tabla("", false));
            break;
            case 1:
                try {
                    if(!txtBusqueda.getText().isEmpty()){
                        String texto = "where t.folio = "+txtBusqueda.getText();
                        tablaTraspaso.setModel(tra.tabla(texto, true));
                    }
                } catch (Exception e) {
                }
            break;
            case 2:
                try{
                    if(!txtBusqueda.getText().isEmpty()){
                        String texto = "where a.nombreA = '"+txtBusqueda.getText()+"'";
                        tablaTraspaso.setModel(tra.tabla(texto, true));
                    }
                } catch (Exception e) {
                }
            break;
            case 3:
                try {
                    if(!txtBusqueda.getText().isEmpty()){
                        String texto = "where t.destino = '"+txtBusqueda.getText()+"'";
                        tablaTraspaso.setModel(tra.tabla(texto, true));
                    }
                } catch (Exception e) {
                }
            break;
            case 4:
            break;
            case 5:
            break;
        }
        
        tablaTraspaso.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaTraspaso.getColumnModel().getColumn(0).setMaxWidth(50);
        tablaTraspaso.getColumnModel().getColumn(1).setMinWidth(85);
        tablaTraspaso.getColumnModel().getColumn(2).setMinWidth(85);
        tablaTraspaso.getColumnModel().getColumn(3).setMinWidth(80);
        tablaTraspaso.getColumnModel().getColumn(4).setMaxWidth(60);
        tablaTraspaso.getColumnModel().getColumn(5).setMaxWidth(80);
        tablaTraspaso.setAutoCreateRowSorter(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panBotones;
    private javax.swing.JPanel panHerramientas;
    private javax.swing.JTable tablaTraspaso;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
